"""empty message

Revision ID: 44e6d4070896
Revises: 9aafac3ee9a2
Create Date: 2025-11-09 13:33:29.630086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e6d4070896'
down_revision: Union[str, None] = '9aafac3ee9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_sessions_last_activity'), 'sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_activity'), table_name='sessions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
